# Default task schedules configuration
# Copy this file and modify schedules as needed

schedules:
  # Monitoring tasks - frequent execution for health checks
  monitoring/console_health_monitor:
    cron: "*/30 * * * *"       # Every 30 minutes
    enabled: true
    max_runtime: 600           # 10 minutes
    retry_count: 2
    config:
      debug: false
      device_list_file: "/var/www/html/info-hub/Console_Inventory/console_total.csv"

  monitoring/dns_availability_monitor:
    cron: "*/15 * * * *"       # Every 15 minutes
    enabled: true
    max_runtime: 300           # 5 minutes
    retry_count: 1
    config:
      debug: false
      test_domains:
        - "short-ttl.ikea.com"
        - "www.ikea.com"
        - "www.google.com"

  # Hardware refresh tasks - during maintenance windows
  hardware/refresh_ansible_hwinfo:
    cron: "0 2 * * *"          # Daily at 2 AM
    enabled: true
    max_runtime: 3600          # 1 hour
    retry_count: 2
    config:
      debug: false
      git_repo_path: "/app/git-repos/IPAM_Data/playbook_report"
      ipam_seed_file: "/var/www/html/info-hub/Network_Inventory/mgmtip_total.csv"

  # Additional hardware refresh tasks (disabled by default)
  # Enable as needed when implementing additional scripts
  
  # hardware/refresh_palo_hwinfo:
  #   cron: "0 3 * * *"          # Daily at 3 AM
  #   enabled: false
  #   max_runtime: 1800          # 30 minutes
  #   retry_count: 2
  
  # hardware/refresh_versa_hwinfo:
  #   cron: "0 4 * * *"          # Daily at 4 AM
  #   enabled: false
  #   max_runtime: 1800          # 30 minutes
  #   retry_count: 2
  
  # discovery/mgmt_network_discovery:
  #   cron: "0 6 * * 0"          # Weekly on Sunday at 6 AM
  #   enabled: false
  #   max_runtime: 7200          # 2 hours
  #   retry_count: 1
  
  # integration/lcm_eox_sync:
  #   cron: "0 5 * * 1"          # Weekly on Monday at 5 AM
  #   enabled: false
  #   max_runtime: 3600          # 1 hour
  #   retry_count: 2